musicapp/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
end

musicapp/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  year       :integer          not null
#  band_id    :bigint           not null
#  studio     :boolean          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Album < ApplicationRecord
  validates :title, presence: true, uniqueness: { scope: :band_id }
  validates :year, presence: true 
  validates :band_id, presence: true 
  validates :studio, presence: true 

  belongs_to :band,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Band
end

musicapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

musicapp/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :albums,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Album,
    dependent: :destroy
end

musicapp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
  validates :email, :session_token, presence: true, uniqueness: true 
  validates :password_digest, presence: true 
  validates :password, length: { minimum: 6 }, allow_nil: true

  before_validation :ensure_session_token

  attr_reader :password 

  def reset_session_token!
    self.session_token = generate_unique_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end

  def is_password?(password)
    password_object = BCrypt::Password.new(self.password_digest)
    password_object.is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user && user.is_password?(password)
      user
    else
      nil 
    end
  end

  private
  def generate_unique_session_token
    loop do 
      session_token = SecureRandom::urlsafe_base64(16)
      return session_token unless User.exists?(session_token: session_token)
    end
  end

  def ensure_session_token
    self.session_token ||= generate_unique_session_token
  end
end

musicapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # skip_before_action :verify_authenticity_token
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logged_in?
    !!current_user 
  end

  def logout!
    current_user.reset_session_token! if logged_in?
    session[:session_token] = nil 
    @current_user = nil 
  end

  def require_logged_in
    redirect_to new_session_url if !logged_in?
  end

  def require_logged_out
    redirect_to user_url(current_user) if logged_in?
  end
end

musicapp/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all 
    render :index # Shows all bands
  end

  def create 
    @band = Band.new(band_params)
    if @band.save 
      redirect_to band_url(@band) 
    else 
      flash.now[:errors] = @band.errors.full_messages
      render :new 
    end
  end

  def new
    @band = Band.new
    render :new # Form to create new band
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit # Form to edit band
  end

  def update
    @band = Band.find_by(id: params[:id])

    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def show
    @band = Band.find_by(id: params[:id])
    render :show # Show one band
  end

  def destroy
    @band = Band.find_by(id: params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

musicapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_logged_out, only: [:create, :new]

  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if user
      login!(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = ["Incorrect username and/or password"]
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

musicapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_out, only: [:create, :new] 

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      # render :show
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

musicapp/app/helpers/application_helper.rb
module ApplicationHelper
end

musicapp/app/helpers/bands_helper.rb
module BandsHelper
end

musicapp/app/helpers/sessions_helper.rb
module SessionsHelper
end

musicapp/app/helpers/users_helper.rb
module UsersHelper
end

musicapp/app/views/bands/edit.html.erb
<section class="page"><div class="centered-box">
  <h1>Edit Band</h1>
  <form action="<%= band_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="PATCH">
    <label for="name">Band Name: </label>
    <input type="text" name="band[name]" id="name" value=<%= @band.name %>>
    <br>
    <br>
    <input type="submit" value="Update Band!">
  </form>
</div></section>

musicapp/app/views/bands/index.html.erb
<h1>All Bands</h1>

<% @bands.each do |band| %>
  <%= band.name %>
  <ul>
    <li><a href="<%= band_url(band) %>">View <%= band.name %></a></li>
    <li><a href="<%= edit_band_url(band) %>">Edit <%= band.name %></a></li>
  </ul>
<% end %>

<a href="<%= new_band_url %>" id="link_button">Create New Band</a>

musicapp/app/views/bands/new.html.erb
<section class="page"><div class="centered-box">
  <h1>Create New Band</h1>
  <form action="<%= bands_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label for="name">Band Name: </label>
    <input type="text" name="band[name]" id="name" value=<%= @band.name %>>
    <br>
    <br>
    <input type="submit" value="Create Band!">
  </form>
</div></section>

musicapp/app/views/bands/show.html.erb
<h1>Band Show Page</h1>
<ul>
  <li><%= @band.name %></li>
</ul>
<a href="<%= edit_band_url(@band) %>">Edit Band</a>

musicapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musicapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <nav class="main-nav">
      <h1 class="logo">Music App</h1>
      <div>
        <% if logged_in? %>
          <p>Logged in as <%= current_user.email %></p>
          <form action="<%= session_url %>" method="post">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="hidden" name="_method" value="delete">
            <input type="submit" value="Logout">
          </form>
        <% else %>
          <a href="<%= new_session_url %>" id="link_button">Sign in</a> 
          <a href="<%= new_user_url %>" id="link_button">Sign up</a> 
        <% end %>
      </div>
    </nav>

    <% if flash[:errors] %>
      <ul>
        <% flash[:errors].each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    <% end %>
    <%= yield %>
  </body>
</html>

musicapp/app/views/users/new.html.erb
<section class="page"><div class="centered-box">
  <h1>New User Sign Up</h1>
  <form action="<%= users_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label for="email">Email: </label>
    <input type="email" name="user[email]" id="email" value="<%= @user.email %>">
    <br>
    <br>
    <label for="password">Password: </label>
    <input type="password" name="user[password]" id="password" value="<%= @user.password %>">
    <br>
    <br>
    <input type="submit" value="Sign Up!">
  </form>
</div></section>

musicapp/app/views/users/show.html.erb
<h1>Profile Page</h1>
<p><%= @user.email %></p>